---
- name: building app boxfuse
  hosts: build-srv
  become: yes

  tasks:
  - name: update package
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: git clone app boxfuse
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /home/ubuntu/app
      clone: yes

  - name: building app
    shell: mvn -f /home/ubuntu/app/boxfuse-sample-java-war-hello/pom.xml package


- name: web app
  hosts: web-srv
  become: yes
  
  tasks:
  - name: update package
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present

  - name: Ensure tomcat start
    service:
      name: tomcat9
      state: started

  - name: Ensure package rsync
    apt: 
      name: rsync
      state: present

  - name: copy war app 
    synchronize:
      src: /home/ubuntu/app/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps
    delegate_to: build-srv